version: '3'

services:
  logservice1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: logservice1
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://db:27017/logs
    ports:
      - "35001:8080"
    depends_on:
      - db

  logservice2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: logservice2
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://db:27017/logs
    ports:
      - "35002:8080"
    depends_on:
      - db

  logservice3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: logservice3
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://db:27017/logs
    ports:
      - "35003:8080"
    depends_on:
      - db

  db:
    image: mongo:3.6.1
    container_name: db
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - "27017:27017"
    command: mongod

volumes:
  mongodb:
  mongodb_config:
